require 'outpost/scouts/http'
require 'outpost/scouts/ping'
require 'outpost/scouts/s_redis'
require 'outpost/scouts/s_mongo'
require 'outpost/scouts/s_telnet'
require 'outpost/scouts/s_kafka'
require 'outpost/scouts/s_postgres'